"""Added columns to order table

Revision ID: 0ed9a9c0be93
Revises: 6f5e7d467ae3
Create Date: 2026-05-18 17:49:39.737152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ed9a9c0be93'
down_revision: Union[str, Sequence[str], None] = '6f5e7d467ae3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('package_size', sa.String(length=20), nullable=False))
    op.add_column('orders', sa.Column('package_weight', sa.String(length=20), nullable=False))
    op.add_column('orders', sa.Column('origin_lat', sa.Float(), nullable=False))
    op.add_column('orders', sa.Column('origin_lng', sa.Float(), nullable=False))
    op.add_column('orders', sa.Column('destination_lat', sa.Float(), nullable=False))
    op.add_column('orders', sa.Column('destination_lng', sa.Float(), nullable=False))
    op.add_column('orders', sa.Column('day_of_week', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('is_festive_period', sa.Boolean(), nullable=False))
    op.add_column('orders', sa.Column('fuel_price_per_litre', sa.Float(), nullable=False))
    op.drop_column('orders', 'length_cm')
    op.drop_column('orders', 'width_cm')
    op.drop_column('orders', 'height_cm')
    op.drop_column('orders', 'weight_kg')
    op.add_column('routes', sa.Column('origin_lat', sa.Float(), nullable=False))
    op.add_column('routes', sa.Column('origin_lng', sa.Float(), nullable=False))
    op.add_column('routes', sa.Column('destination_lat', sa.Float(), nullable=False))
    op.add_column('routes', sa.Column('destination_lng', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routes', 'destination_lng')
    op.drop_column('routes', 'destination_lat')
    op.drop_column('routes', 'origin_lng')
    op.drop_column('routes', 'origin_lat')
    op.add_column('orders', sa.Column('weight_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('height_cm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('width_cm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('length_cm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('orders', 'fuel_price_per_litre')
    op.drop_column('orders', 'is_festive_period')
    op.drop_column('orders', 'day_of_week')
    op.drop_column('orders', 'destination_lng')
    op.drop_column('orders', 'destination_lat')
    op.drop_column('orders', 'origin_lng')
    op.drop_column('orders', 'origin_lat')
    op.drop_column('orders', 'package_weight')
    op.drop_column('orders', 'package_size')
    # ### end Alembic commands ###
