"""Changed column from predicted_price to price

Revision ID: 568c3c3b86e7
Revises: 781cf48ee739
Create Date: 2026-05-25 21:50:41.300345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '568c3c3b86e7'
down_revision: Union[str, Sequence[str], None] = '781cf48ee739'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('price', sa.Float(), nullable=False))
    op.add_column('orders', sa.Column('confidence_band_low', sa.Float(), nullable=False))
    op.add_column('orders', sa.Column('confidence_band_high', sa.Float(), nullable=False))
    op.add_column('orders', sa.Column('model_used', sa.String(length=20), nullable=False))
    op.drop_column('orders', 'predicted_price')
    op.drop_column('orders', 'actual_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('actual_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('predicted_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('orders', 'model_used')
    op.drop_column('orders', 'confidence_band_high')
    op.drop_column('orders', 'confidence_band_low')
    op.drop_column('orders', 'price')
    # ### end Alembic commands ###
