"""Added nullable to vehicle type in users creation

Revision ID: 781cf48ee739
Revises: 0ed9a9c0be93
Create Date: 2026-05-18 19:27:39.114788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '781cf48ee739'
down_revision: Union[str, Sequence[str], None] = '0ed9a9c0be93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'vehicle_type',
               existing_type=postgresql.ENUM('SMALL_CAR', 'BIG_BUS', name='vehicletype'),
               nullable=True)
    op.alter_column('users', 'plate_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('users', 'state_of_operation',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('users', 'nin_license',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'nin_license',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'state_of_operation',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('users', 'plate_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('users', 'vehicle_type',
               existing_type=postgresql.ENUM('SMALL_CAR', 'BIG_BUS', name='vehicletype'),
               nullable=False)
    # ### end Alembic commands ###
